#!/usr/bin/env bash
# Review every command; this script is intentionally not executed by the repository.
set -euo pipefail
export AWS_REGION=us-east-2
export NAME="eia-lab-$(date +%s)"; export VPC_CIDR=10.42.0.0/16; export TRUSTED_CIDR=127.0.0.1/32
# 1) Network (capture IDs from each JSON response).
VPC_ID=$(aws ec2 create-vpc --cidr-block "$VPC_CIDR" --region "$AWS_REGION" --query Vpc.VpcId --output text)
aws ec2 modify-vpc-attribute --vpc-id "$VPC_ID" --enable-dns-support Value=true; aws ec2 modify-vpc-attribute --vpc-id "$VPC_ID" --enable-dns-hostnames Value=true
IGW_ID=$(aws ec2 create-internet-gateway --query InternetGateway.InternetGatewayId --output text); aws ec2 attach-internet-gateway --vpc-id "$VPC_ID" --internet-gateway-id "$IGW_ID"
AZ1=$(aws ec2 describe-availability-zones --region "$AWS_REGION" --filters Name=state,Values=available --query 'AvailabilityZones[0].ZoneName' --output text); AZ2=$(aws ec2 describe-availability-zones --region "$AWS_REGION" --filters Name=state,Values=available --query 'AvailabilityZones[1].ZoneName' --output text)
PUB=$(aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block 10.42.1.0/24 --availability-zone "$AZ1" --query Subnet.SubnetId --output text); P1=$(aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block 10.42.10.0/24 --availability-zone "$AZ1" --query Subnet.SubnetId --output text); P2=$(aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block 10.42.11.0/24 --availability-zone "$AZ2" --query Subnet.SubnetId --output text)
for resource in "$VPC_ID" "$IGW_ID" "$PUB" "$P1" "$P2"; do aws ec2 create-tags --resources "$resource" --tags Key=Project,Value=EIA-AWS-Activity Key=Environment,Value=Lab Key=ManagedBy,Value=OMP; done
RT=$(aws ec2 create-route-table --vpc-id "$VPC_ID" --query RouteTable.RouteTableId --output text); aws ec2 create-route --route-table-id "$RT" --destination-cidr-block 0.0.0.0/0 --gateway-id "$IGW_ID"; aws ec2 associate-route-table --route-table-id "$RT" --subnet-id "$PUB"; aws ec2 modify-subnet-attribute --subnet-id "$PUB" --map-public-ip-on-launch; aws ec2 create-tags --resources "$RT" --tags Key=Project,Value=EIA-AWS-Activity Key=Environment,Value=Lab Key=ManagedBy,Value=OMP
EC2_SG=$(aws ec2 create-security-group --group-name "$NAME-ec2" --description lab --vpc-id "$VPC_ID" --query GroupId --output text); RDS_SG=$(aws ec2 create-security-group --group-name "$NAME-rds" --description postgres --vpc-id "$VPC_ID" --query GroupId --output text); aws ec2 create-tags --resources "$EC2_SG" "$RDS_SG" --tags Key=Project,Value=EIA-AWS-Activity Key=Environment,Value=Lab Key=ManagedBy,Value=OMP; aws ec2 authorize-security-group-ingress --group-id "$EC2_SG" --protocol tcp --port 22 --cidr "$TRUSTED_CIDR"; aws ec2 authorize-security-group-ingress --group-id "$RDS_SG" --protocol tcp --port 5432 --source-group "$EC2_SG"
 # 2) S3, EC2, RDS.
BUCKET="eia-aws-activity-$NAME"; aws s3api create-bucket --bucket "$BUCKET" --region "$AWS_REGION" --create-bucket-configuration LocationConstraint="$AWS_REGION"; aws s3api put-bucket-tagging --bucket "$BUCKET" --tagging 'TagSet=[{Key=Project,Value=EIA-AWS-Activity},{Key=Environment,Value=Lab},{Key=ManagedBy,Value=OMP}]'; aws s3api put-public-access-block --bucket "$BUCKET" --public-access-block-configuration BlockPublicAcls=true,BlockPublicPolicy=true,IgnorePublicAcls=true,RestrictPublicBuckets=true; aws s3api put-bucket-encryption --bucket "$BUCKET" --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'; aws s3api put-bucket-lifecycle-configuration --bucket "$BUCKET" --lifecycle-configuration '{"Rules":[{"ID":"expire-lab-objects","Status":"Enabled","Filter":{"Prefix":""},"Expiration":{"Days":7}}]}'
AMI=$(aws ssm get-parameter --name /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64 --query Parameter.Value --output text); INSTANCE=$(aws ec2 run-instances --image-id "$AMI" --instance-type t3.micro --subnet-id "$PUB" --security-group-ids "$EC2_SG" --metadata-options HttpTokens=required,HttpEndpoint=enabled,HttpPutResponseHopLimit=1 --block-device-mappings 'DeviceName=/dev/xvda,Ebs={VolumeSize=8,VolumeType=gp3,Encrypted=true,DeleteOnTermination=true}' --query Instances[0].InstanceId --output text); aws ec2 create-tags --resources "$INSTANCE" --tags Key=Project,Value=EIA-AWS-Activity Key=Environment,Value=Lab Key=ManagedBy,Value=OMP
DB="eia-lab-$NAME"; aws rds create-db-subnet-group --db-subnet-group-name "$DB" --db-subnet-group-description lab --subnet-ids "$P1" "$P2"; aws rds create-db-instance --db-instance-identifier "$DB" --engine postgres --engine-version 16 --db-instance-class db.t3.micro --allocated-storage 20 --max-allocated-storage 20 --storage-type gp3 --storage-encrypted --db-name eia --master-username eiaadmin --manage-master-user-password --db-subnet-group-name "$DB" --vpc-security-group-ids "$RDS_SG" --no-publicly-accessible --backup-retention-period 0 --no-multi-az --no-deletion-protection
aws rds add-tags-to-resource --resource-name "arn:aws:rds:$AWS_REGION:$(aws sts get-caller-identity --query Account --output text):db:$DB" --tags Key=Project,Value=EIA-AWS-Activity Key=Environment,Value=Lab Key=ManagedBy,Value=OMP
# 3) Verify then destroy in reverse order. Never omit the RDS subnet group or non-empty S3 objects.
aws ec2 describe-instances --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].State.Name'; aws rds describe-db-instances --db-instance-identifier "$DB" --query 'DBInstances[0].DBInstanceStatus'; aws s3api head-bucket --bucket "$BUCKET"
printf '{"timestamp_utc":"%s","method":"aws-cli","region":"%s","bucket":"%s","instance":"%s","db":"%s","vpc":"%s","igw":"%s","public_subnet":"%s","private_subnets":["%s","%s"],"route_table":"%s","ec2_sg":"%s","rds_sg":"%s","ec2_status":"%s","rds_status":"%s","s3_head":"ok"}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$AWS_REGION" "$BUCKET" "$INSTANCE" "$DB" "$VPC_ID" "$IGW_ID" "$PUB" "$P1" "$P2" "$RT" "$EC2_SG" "$RDS_SG" "$(aws ec2 describe-instances --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].State.Name' --output text)" "$(aws rds describe-db-instances --db-instance-identifier "$DB" --query 'DBInstances[0].DBInstanceStatus' --output text)" > evidence/cli-create-verify.json
aws rds delete-db-instance --db-instance-identifier "$DB" --skip-final-snapshot --delete-automated-backups; aws rds wait db-instance-deleted --db-instance-identifier "$DB"; aws rds delete-db-subnet-group --db-subnet-group-name "$DB"; aws ec2 terminate-instances --instance-ids "$INSTANCE"; aws ec2 wait instance-terminated --instance-ids "$INSTANCE"; aws s3 rm "s3://$BUCKET" --recursive; aws s3api delete-bucket --bucket "$BUCKET"; aws ec2 delete-security-group --group-id "$RDS_SG"; aws ec2 delete-security-group --group-id "$EC2_SG"; aws ec2 disassociate-route-table --association-id "$(aws ec2 describe-route-tables --route-table-ids "$RT" --query 'RouteTables[0].Associations[0].RouteTableAssociationId' --output text)"; aws ec2 delete-route-table --route-table-id "$RT"; for subnet in "$PUB" "$P1" "$P2"; do aws ec2 delete-subnet --subnet-id "$subnet"; done; aws ec2 detach-internet-gateway --internet-gateway-id "$IGW_ID" --vpc-id "$VPC_ID"; aws ec2 delete-internet-gateway --internet-gateway-id "$IGW_ID"; aws ec2 delete-vpc --vpc-id "$VPC_ID"
set +e; aws s3api head-bucket --bucket "$BUCKET" --region "$AWS_REGION" >/tmp/cli-s3-absent 2>&1; S3_RC=$?; aws ec2 describe-instances --instance-ids "$INSTANCE" --region "$AWS_REGION" >/tmp/cli-ec2-absent 2>&1; EC2_RC=$?; aws rds describe-db-instances --db-instance-identifier "$DB" --region "$AWS_REGION" >/tmp/cli-rds-absent 2>&1; RDS_RC=$?; aws ec2 describe-vpcs --vpc-ids "$VPC_ID" --region "$AWS_REGION" >/tmp/cli-vpc-absent 2>&1; VPC_RC=$?; aws resourcegroupstaggingapi get-resources --region "$AWS_REGION" --tag-filters Key=Project,Values=EIA-AWS-Activity > evidence/cli-tag-audit.json; printf '{"timestamp_utc":"%s","method":"aws-cli","absence_rc":{"s3":%s,"ec2":%s,"rds":%s,"vpc":%s},"expected_notfound":true}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$S3_RC" "$EC2_RC" "$RDS_RC" "$VPC_RC" > evidence/cli-destroy-verify.json; set -e
# Verification should return ResourceNotFound/NotFound for the deleted IDs and no matching tagged resources.
